name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup PostgreSQL
      uses: bmizerany/setup-postgres@v3
      with:
        version: '13.14.0'

    - name: Install Poetry
      run: |
        pip install poetry
        poetry config virtualenvs.create false

    - name: Install dependencies
      run: poetry install

    - name: Run unit tests
      run: poetry run pytest -m "not integration"

    - name: Run integration tests
      env:
        PML_DB_CONNECTION_STRING: postgresql://postgres:postgres@localhost:5432/postgres
      run: poetry run pytest -m "integration"
